---
- name: Create User
  hosts: 54.163.212.73 
  become: true  

  tasks:
    - name: Add user
      user:
        name: usernew
        password: "{{ 'khush@123' | password_hash('sha512') }}"
        state: present
        groups: wheel
        create_home: yes

